const initialState = {
  adminDash: {
    items: [
      'AllUser',
      'Users',
      'Accounts',
      'Transactions',
      'Requests',
      'Coin Deposits',
      'Notification',
      'Email',
      'Announcement',
      'Orders',
      'Trades',
    ],
    userAttr: [
      'UserID',
      'Name',
      'Email',
      'Phone',
      'IsVerified',
      'KYCVerified',
      'Action',
    ],
    orderAttr: [
      'OrderID',
      'UserID',
      'Side',
      'Currency',
      'Price',
      'Current Size',
      'Filled Size',
      'Status',
      'CreatedAt',
    ],
    accountAttr: [
      'Name',
      'Currency',
      'Value',
      'AccountID',
      'UserID',
      'Address',
      'Action',
    ],
    tradeAttr: [
      'TradeID',
      'Price',
      'Size',
      'Cost Applied',
      'BuyerID',
      'SellerID',
      'CreatedAt',
    ], // BuyerOrderId, SellerOrderId can be added
    transaAttr: [
      'CustomerID',
      'Currency',
      'Amt',
      'Address',
      'Type',
      'Status',
      'updatedAt',
      'Actions',
    ],
    allUsers: [],
    allOrders: [],
    allAccounts: [],
    allTrades: [],
    allTransactions: [],
    usersData: [],
    ordersData: [],
    accountsData: [],
    tradesData: [],
    transactionsData: [],
    activeItem: 'AllUser',
    userDoc: {},
    announcement: '',
  },
  app: {},
  wallets: {},
  requests: [],
  transactions: {},
  transactionJobs: {},
  userJobs: {},
  jobs: {},
  users: {}, // [id]: details
  statements: {}, // [id]: statement
};

export default initialState;
